# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '''
($username@$hostname:)$directory$git_branch
$character
'''

follow_symlinks = false
scan_timeout = 10

[hostname]
format = '[$hostname]($style)'

[username]
format = '[$user]($style)'
